name: clinic_brayka
description: A medical clinic app for managing medicines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
